declare module '*.ico';
declare module '*.png';
declare module '*.jpg';
declare module '*.svg';
declare module '*.eot';
declare module '*.ttf';
declare module '*.otf';
declare module '*.woff';
declare module '*.woff2';